name: Suggestion
description: Suggest a change or something new.
labels: ['Suggestion']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to submit a suggestion!
  - type: textarea
    id: page-view
    attributes:
      label: Describe The Suggestion
      description: A clear and concise description.
      placeholder: Tell us what you want to see!
      value: 'As a... I want... So that...'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the page here.
    validations:
      required: false
