name: raven
description: Ravencoin Wallet Library
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bs58check: ^1.0.2
  collection: ^1.15.0
  crypto: ^3.0.0
  encrypt: ^5.0.0
  equatable: ^2.0.3
  hive: ^2.0.4
  ordered_set: ^3.1.0
  pointycastle: ^3.3.4
  quiver: ^3.0.1
  #ravencoin: ^2.1.0
  #raven_electrum_client: ^1.2.1
  reservoir: ^4.0.1
  rxdart: ^0.27.1
  sorted_list: ^1.0.0
  http: ^0.13.3
  ulid: ^2.0.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  date_format: ^2.0.4
  dotenv: ^3.0.0
  hive_generator: ^1.1.0
  pedantic: ^1.10.0
  test: ^1.17.12

dependency_overrides:
  reservoir:
    path: ../reservoir
  raven_electrum_client:
    path: ../raven_electrum_client
  ravencoin:
    path: ../ravencoin