name: raven
description: Ravencoin Wallet Library
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bitcoin_flutter: ^2.0.2
  http: ^0.13.3
  json_rpc_2: ^3.0.1
  stream_channel: ^2.1.0
  rxdart: ^0.27.1
  crypto: ^2.0.3
  equatable: ^2.0.3
  timing: ^1.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
