name: bitcoin_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/anicdh
author: andoan <anic.dh@gmail.com>

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  bip39: ^1.0.3
  bip32: ^1.0.2
  pointycastle: ^1.0.0-rc2
  hex: ^0.1.2
  bs58check: ^1.0.1

dev_dependencies:
  test: ^1.0.0
