name: raven_front
description: A Ravencoin wallet for iOS and Android 

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  barcode_scan2: ^4.1.4
  cupertino_icons: ^1.0.2
  datadog_flutter: ^1.4.0
  date_format: ^2.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_spinkit: ^5.0.0
  flutter_treeview: ^1.0.6+1
  flutter_launcher_icons: '^0.9.1'
  fnv: ^1.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.6.1
  settings_ui: ^1.0.0
  ulid: ^2.0.0
  url_launcher: ^6.0.10
  #ravencoin: ^2.1.0
  path_provider: ^2.0.5 # to get the correct path to store our file
  permission_handler: ^8.2.5 # to handle the permissions to read and write files
  share: ^2.0.4 # to share the file that we create
  file_picker: ^4.1.5 # to import the file that we saved
  intl: ^0.17.0

  # MoonTree in-house dependencies
  raven_back:
    git: https://github.com/moontreeapp/raven_back.git
  raven_electrum_client: ^1.2.1
  reservoir: ^2.0.0

dependency_overrides:
  raven_back:
    path: ../raven_back
    #git: https://github.com/moontreeapp/raven_back.git
  raven_electrum_client:
    path: ../raven_electrum
    #git: https://github.com/moontreeapp/raven_electrum.git
  reservoir:
    path: ../reservoir
    #git: https://github.com/moontreeapp/reservoir.git
  ravencoin:
    path: ../ravencoin_wallet
    #git: https://github.com/moontreeapp/ravencoin_wallet.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.17.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/splash/
    - assets/spinner/
    - assets/logo/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
